.job_template: &job_build
  stage: build
  before_script:
    - echo Restore node modules ...
    - cd reactdemoapp && npm install
  tags:
    - macosbuild

.job_template: &job_deploy
  stage: deploy
  before_script:
    - echo Restore node modules ...
    - cd reactdemoapp && npm install
  tags:
    - macosbuild
  after_script:
    - cp $OUTPUT_PATH.$FILE_TYPE $CI_PROJECT_NAME-$CI_MERGE_REQUEST_TARGET_BRANCH_NAME.$FILE_TYPE
  artifacts:
    name: "$CI_PROJECT_NAME-$PLATFORM-$CI_MERGE_REQUEST_TARGET_BRANCH_NAME"
    paths:
      - $CI_PROJECT_NAME-$CI_MERGE_REQUEST_TARGET_BRANCH_NAME.$FILE_TYPE
    expire_in: 7 days

build:android:
  <<: *job_build
  script:
    - echo Creating Android App Bundle ...
    - cd android && ./gradlew assembleRelease -PMYAPP_RELEASE_STORE_PASSWORD=$KEYSTORE_PASSWORD -PMYAPP_RELEASE_KEY_PASSWORD=KEYSTORE_PASSWORD

deploy:android:uitest:
  variables:
    PLATFORM: android
    FILE_TYPE: apk
    OUTPUT_PATH: reactdemoapp/android/app/build/outputs/apk/release/app-release
    TEST_BUILD_PATH: reactdemoapp-uitest/reactdemoapp-uitest.Droid/bin/Debug
    UITEST_TOOL_PATH: reactdemoapp-uitest/packages/Xamarin.UITest.3.0.9/tools/
  <<: *job_deploy
  rules:
    - if: '$CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "main"'
  script:
    - echo Creating Android App Bundle ...
    - cd android && ./gradlew assembleRelease -PMYAPP_RELEASE_STORE_PASSWORD=$KEYSTORE_PASSWORD -PMYAPP_RELEASE_KEY_PASSWORD=KEYSTORE_PASSWORD
    - echo Restoring nuget Packages ...
    - cd ../../reactdemoapp-uitest && nuget restore
    - echo Building Xamarin UI Test Project ...
    - msbuild reactdemoapp-uitest.sln /p:Configuration=Debug /p:Platform="Any CPU"
    - cd ..
    - appcenter test run uitest --app "brandung-GmbH-Co.-KG/reactnative-uitest" --devices "brandung-GmbH-Co.-KG/demo" --app-path $OUTPUT_PATH.$FILE_TYPE --test-series "master" --locale "en_US" --build-dir $TEST_BUILD_PATH --uitest-tools-dir $UITEST_TOOL_PATH
