name: Continuous Integration

on:
  push:
    branches:
      - main

defaults:
  run:
    working-directory: ./reactdemoapp

jobs:
  beta-distribution:
    runs-on: windows-latest
    env:
      working-directory: ./reactdemoapp
    name: Beta Distribution
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: actions/setup-node@master
        with:
          node-version: 14.x
      # - uses: c-hive/gha-yarn-cache@v1

      - name: Install node modules
        run: |
          yarn install
      - name: Cache Gradle Wrapper
        uses: actions/cache@v2
        with:
          path: ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-wrapper-${{ hashFiles('gradle/wrapper/gradle-wrapper.properties') }}

      - name: Cache Gradle Dependencies
        uses: actions/cache@v2
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-caches-${{ hashFiles('gradle/wrapper/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-caches-
      - name: Make Gradlew Executable
        run: cd android && chmod +x ./gradlew

      - name: Build Android App Bundle
        run: |
          cd android && ./gradlew bundleDebug --no-daemon

      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: Debug App Bundle
          path: android/app/build/outputs/apk/debug/app-debug.apk

      - uses: actions/setup-dotnet@v1
      - run: cd ../reactdemoapp-uitest && dotnet build reactdemoapp-uitest.sln
